name: Build and Deploy

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays at midnight UTC

# Add permissions to allow deployment
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Website
        uses: actions/checkout@v3

      - name: Checkout Model Zoo
        uses: actions/checkout@v3
        with:
          repository: Project-MONAI/model-zoo
          path: scripts/model-zoo

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install requests beautifulsoup4 markdown

      - name: Fetch and process model data
        run: python scripts/fetch.py

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: |
          echo "Building Tailwind CSS..."
          npx tailwindcss -i ./assets/css/style.css -o ./dist/assets/css/tailwind.css --minify
          
      - name: Build model-zoo.js
        run: |
          echo "Building model-zoo.js..."
          mkdir -p dist/assets/js
          npx babel src/model-zoo.js --out-file dist/model-zoo.js --presets=@babel/preset-env,@babel/preset-react --plugins=@babel/plugin-transform-react-jsx
          
      - name: Build site
        run: npm run build

      - name: Copy assets and data
        run: |
          # Create necessary directories
          mkdir -p dist/assets/css
          mkdir -p dist/assets/js
          mkdir -p dist/assets/fonts
          mkdir -p dist/assets/img
          
          # Copy all assets maintaining directory structure
          cp -r assets/* dist/assets/
          
          # Preserve the built model-zoo.js
          mv dist/model-zoo.js dist/model-zoo.js.built || true
          
          # Copy other necessary directories and files
          cp -r apps dist/ || true
          cp -r research dist/ || true
          cp -r images dist/ || true
          cp -r src/* dist/ || true
          
          # Restore the built version
          mv dist/model-zoo.js.built dist/model-zoo.js || true
          
          cp scripts/model_data.json dist/ || true
          
          # Debug output for model_data.json
          echo "Checking model_data.json locations:"
          find . -name model_data.json -ls
          
          # Ensure proper file permissions
          find dist -type f -name "*.css" -exec chmod 644 {} \;
          find dist -type f -name "*.js" -exec chmod 644 {} \;
          find dist -type f -name "*.html" -exec chmod 644 {} \;
          find dist -type f -name "*.json" -exec chmod 644 {} \;
          
          # Debug output
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of dist/assets:"
          ls -la dist/assets/
          
          # Verify model-zoo.js
          echo "First few lines of model-zoo.js:"
          head -n 5 dist/model-zoo.js || true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true # Automatically remove deleted files from the deployment 